# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.0-1-g09d86e1
_src_path: ../copier-cpp-cmake
ci_system: Github
cmake_min_version: '3.23'
code_coverage: false
cpp_standard: 17
dependencies: conan-1.x
include_what_you_use: false
license: MIT License
license_owner: Maciej Patro
project_name: My Project
project_namespace: mp
project_setup: expert
project_slug: my_project
project_type: single executable
sanitize: false
unit_testing_11: doctest
unit_testing_14: doctest
unit_testing_17: doctest
unit_testing_98: GTest

