name: build-and-test

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - ubuntu-20.04-clang-14
          - ubuntu-20.04-clang-13
          - ubuntu-20.04-clang-12
          - ubuntu-20.04-gcc-11
          - ubuntu-20.04-gcc-10
          - ubuntu-20.04-gcc-9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/conan-cache
      - uses: docker://${{ matrix.configuration }}
      - run: |
          cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build release
          ctest --test-dir release -VV
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: './release/*_tests.xml'
