name: build-and-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-20.04-clang-14
          - ubuntu-20.04-clang-13
          - ubuntu-20.04-clang-12
          - ubuntu-20.04-gcc-11
          - ubuntu-20.04-gcc-10
          - ubuntu-20.04-gcc-9
    steps:
      - uses: actions/checkout@v2
      - uses: docker://${{ matrix.image }}
      - uses: ./.github/actions/conan-cache
      - run: |
          cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build release
          ctest --test-dir release -VV
