name: build-and-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo docker://${{ matrix.image }}
