name: build-and-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo docker://${{ matrix.os }}
