name: code-coverage

on: [push, pull_request]

jobs:
  test:
    container: docker://maciejpatro/ubuntu-20.04-clang-13-with-tools
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/conan-cache
      - uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build and test
        run: |
          cmake -B coverage -G Ninja -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON
          cmake --build coverage
#          ctest --test-dir coverage -VV
#          gcovr --xml-pretty --delete --print-summary --root ${GITHUB_WORKSPACE} \
#              --xml coverage.xml --gcov-executable 'llvm-cov gcov'
      - uses: github/codeql-action/analyze@v1
